version: "1.0"


services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: "write-djngo"

    restart: always
    expose:
      - "8000"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
